---
- name: Add Dependecies
  hosts: free-m
  remote_user: root
  tasks:
  - name: Ensure GPG
    apt:
      name: gnupg
      state: present
      update_cache: yes

- name: Provision Free m
  hosts: free-m
  remote_user: root
  roles:
    - jdauphant.nginx
    - geerlingguy.java
    - { role: geerlingguy.jenkins,
        jenkins_hostname: localhost,
        jenkins_admin_username: admin,
        jenkins_admin_password: admin,
        jenkins_plugins: [sonar, nexus-jenkins-plugin],
        jenkins_updates_url: "https://updates.jenkins.io",
        jenkins_plugins_install_dependencies: true,
        use_proxy:false,
        jenkins_plugins_state: present }
  tasks:
    - name: Create nginx config
      template:
        src: "nginx.conf.j2"
        dest: /etc/nginx/sites-available/free-m
        owner: root
        group: root
        mode: 0755

    - name: Link nginx config
      file:
        state: link
        src: '/etc/nginx/sites-available/free-m'
        path: '/etc/nginx/sites-enabled/free-m'
        owner: root
        group: root
        mode: 0755
        
    - name: Remove default config
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/nginx/sites-available/default.conf"
        - "/etc/nginx/sites-available/default"
        - "/etc/nginx/sites-enabled/default.conf"
        - "/etc/nginx/sites-enabled/default"
      notify:
        - restart nginx

